In [65]:
### Carregar as Libraries
import numpy as np
import pandas as pd

### Importing Dataset
dataset = pd.read_csv('Madelon.csv',encoding='utf-8')

### Mostrando as colunas do dataset
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2600 entries, 0 to 2599
Columns: 501 entries, a_0 to classe
dtypes: int64(501)
memory usage: 9.9 MB


In [ ]:
tipos_numericos = ['int64']
atributos_numericos = dataset.select_dtypes(include=tipos_numericos)

colunas_numericas = list(atributos_numericos.columns)

print(colunas_numericas)

X = dataset[colunas_numericas] # Features
y = dataset.classe      # Target variable (classe)

print(X)

In [67]:
### Importando PCA do SkLearn #################

from sklearn.decomposition import PCA

##pca_obj = PCA(n_components=4)
pca_obj = PCA(n_components=0.20, whiten=True)
pca_result = pca_obj.fit_transform(X)

print(pca_result.shape)

columns = ["pca_"+str(i) for i in range(1,pca_result.shape[1]+1)]

print(columns)
pca_dataset = pd.DataFrame(data = pca_result, columns=columns)

(2600, 3)
['pca_1', 'pca_2', 'pca_3']


In [68]:
final_data = pca_dataset.join(y)

final_data.head()

df = pd.DataFrame(final_data)
df.to_csv('Madelon_PCA.csv', index=False)

# Importando arquivo transformado
#from google.colab import files
#files.download('Madelon_PCA.csv')

In [69]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
from sklearn.metrics import confusion_matrix

### Importing Dataseta
data = pd.read_csv('Madelon_PCA.csv',encoding='utf-8')

#split dataset in features and target variable
tipos_numericos = ['int64', 'float64']
atributos_numericos = data.select_dtypes(include=tipos_numericos)

## selecionando as colunas
colunas_numericas = list(atributos_numericos.columns)

X = data[colunas_numericas] # Features
y = data.classe # Target variable

X.drop('classe',inplace=True,axis=1)#dropei a classe porque ela estava entrando no cálculo pelo y também, já que era int64 tbm, e não podia!!

# Split dataset into training set and test set
X_train_70, X_test_30, y_train_70, y_test_30 = train_test_split(X, y, test_size=0.3, random_state=1) # 70% training and 30% test

# Create KNeighborsClassifier object
knn = KNeighborsClassifier(n_neighbors=1, metric='euclidean')
knn.fit(X_train_70, y_train_70)

#Predict the response for test dataset
y_pred = knn.predict(X_test_30)

# Model Accuracy, how often is the classifier correct?
acuracia = metrics.accuracy_score(y_test_30, y_pred)
print('Accuracy of Madelon_PCA: %.3f' % acuracia)

# Matriz de confusão p/ 30%
confusion_matrix(y_test_30, y_pred)

Accuracy of Madelon_PCA: 0.672


array([[268, 128],
       [128, 256]])

In [70]:
### Importing Dataset
data = pd.read_csv('Madelon.csv',encoding='utf-8')

#split dataset in features and target variable
tipos_numericos = ['int64', 'float64']
atributos_numericos = data.select_dtypes(include=tipos_numericos)

## selecionando as colunas
colunas_numericas = list(atributos_numericos.columns)

X = data[colunas_numericas] # Features
y = data.classe # Target variable

X.drop('classe',inplace=True,axis=1) #dropei a classe porque ela estava entrando no cálculo pelo y também, já que era int64 tbm, e não podia!!
# Split dataset into training set and test set
X_train_70, X_test_30, y_train_70, y_test_30 = train_test_split(X, y, test_size=0.3, random_state=1) # 70% training and 30% test

# Create KNeighborsClassifier object
knn = KNeighborsClassifier(n_neighbors=1, metric='euclidean')
knn.fit(X_train_70, y_train_70)

#Predict the response for test dataset
y_pred = knn.predict(X_test_30)

# Model Accuracy, how often is the classifier correct?
acuracia = metrics.accuracy_score(y_test_30, y_pred)
print('Accuracy of Madelon: %.3f' % acuracia)

# Matriz de confusão p/ 30%
confusion_matrix(y_test_30, y_pred)

Accuracy of Madelon: 0.633


array([[249, 147],
       [139, 245]])

In [ ]:
### Importando LDA do SkLearn
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

lda_obj = LinearDiscriminantAnalysis(n_components=1)
lda_result = lda_obj.fit(X, y).transform(X)
##pca_result = pca_obj.fit_transform(X)

print(lda_result.shape)

lda_dataset = pd.DataFrame(data = lda_result, columns = ['lda_01'])

(2600, 1)


In [ ]:
## Juntando o atributo classe
final_data = lda_dataset.join(y)

# Visualização dos dados normalizados
lda_dataset.head()

# Salvando Pessoa.csv transformado
df = pd.DataFrame(lda_dataset)
df.to_csv('Madelon_LDA.csv', index=False)

# Importando arquivo transformado
#from google.colab import files
#files.download('Madelon_LDA.csv')

In [ ]:
## Juntando o atributo classe
final_data = lda_dataset.join(y)

# Visualização dos dados normalizados
final_data.head()

# Salvando Pessoa.csv transformado
df = pd.DataFrame(final_data)
df.to_csv('Madelon_LDA.csv', index=False)

# Importando arquivo transformado
#from google.colab import files
#files.download('Madelon_LDA.csv')

In [ ]:
### Importing Dataset
data = pd.read_csv('Madelon_LDA.csv',encoding='utf-8')

#split dataset in features and target variable
tipos_numericos = ['int64']
atributos_numericos = data.select_dtypes(include=tipos_numericos)

## selecionando as colunas
colunas_numericas = list(atributos_numericos.columns)

X = data[colunas_numericas] # Features
y = data.classe # Target variable

data.drop('classe',inplace=True,axis=1)
# Split dataset into training set and test set
X_train_70, X_test_30, y_train_70, y_test_30 = train_test_split(X, y, test_size=0.3, random_state=1) # 70% training and 30% test

# Create KNeighborsClassifier object
knn = KNeighborsClassifier(n_neighbors=1, metric='euclidean')
knn.fit(X_train_70, y_train_70)

#Predict the response for test dataset
y_pred = knn.predict(X_test_30)

# Model Accuracy, how often is the classifier correct?
acuracia = metrics.accuracy_score(y_test_30, y_pred)
print('Accuracy of Madelon_LDA: %.3f' % acuracia)

# Matriz de confusão p/ 30%
confusion_matrix(y_test_30, y_pred)

Accuracy of Madelon_LDA: 1.000


array([[396,   0],
       [  0, 384]])